# LED light color message
# rgb values to show
std_msgs/ColorRGBA rgba

# byte value representation
uint8[4] bytes

# some common color combinations
# red
uint8 RED_R = 255
uint8 RED_G = 0
uint8 RED_B = 0
uint8 RED_A = 255

# green
uint8 GREEN_R = 0
uint8 GREEN_G = 255
uint8 GREEN_B = 0
uint8 GREEN_A = 255

# blue
uint8 BLUE_R = 0
uint8 BLUE_G = 0
uint8 BLUE_B = 255
uint8 BLUE_A = 255

# yellow
uint8 YELLOW_R = 255
uint8 YELLOW_G = 255
uint8 YELLOW_B = 0
uint8 YELLOW_A = 255
